---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argo-cd-user-values
  namespace: org-martin
data:
  argocd.yaml: |
    createAggregateRoles: false
    crds:
      install: false
    secret:
      create: true
    controller:
      clusterAdminAccess:
        enabled: false
      replicas: 1
    redis-ha:
      enabled: true
      containerSecurityContext:
        seccompProfile: null
      haproxy:
        containerSecurityContext:
          seccompProfile: null
    server:
      clusterAdminAccess:
        enabled: false
      autoscaling:
        enabled: true
        minReplicas: 2
    repoServer:
      clusterAdminAccess:
        enabled: false
      autoscaling:
        enabled: true
        minReplicas: 2
    applicationSet:
      replicas: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argo-workflows-user-values
  namespace: org-martin
data:
  workflow.yaml: |
    createAggregateRoles: false
    singleNamespace: true
    crds:
      install: false
    controller:
      clusterWorkflowTemplates:
        enabled: false
    server:
     clusterWorkflowTemplates:
       enabled: false
