apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tornado-gitops  # TODO: change "mc-name" to your Management Cluster name
  namespace: default
spec:
  interval: 1m0s
  path: ./management-clusters/tornado
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: tkp-argo-demo  # TODO: change "your-repo" to the name of GitRepository pointing to your gitops repo
  timeout: 2m0s
